[package]
name = "tan-shell"
description = "A shell powered by Tan"
version = "0.11.0"
license = "Apache-2.0"
repository = "https://github.com/tanlang-org/tan-shell"
keywords = ["shell", "tan", "language", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

[dependencies]
